//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace DotNetOutdated.Core.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class ValidationErrorMessages {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("DotNetOutdated.Core.Resources.ValidationErrorMessages", typeof(ValidationErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify which project file to use because the directory &apos;{0}&apos; contains more than one..
        /// </summary>
        internal static string DirectoryContainsMultipleProjects {
            get {
                return ResourceManager.GetString("DirectoryContainsMultipleProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify which solution file to use because the directory &apos;{0}&apos; contains more than one..
        /// </summary>
        internal static string DirectoryContainsMultipleSolutions {
            get {
                return ResourceManager.GetString("DirectoryContainsMultipleSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; does not contain any solutions or projects..
        /// </summary>
        internal static string DirectoryDoesNotContainSolutionsOrProjects {
            get {
                return ResourceManager.GetString("DirectoryDoesNotContainSolutionsOrProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory or file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string DirectoryOrFileDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryOrFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is not a valid solution or project..
        /// </summary>
        internal static string FileNotAValidSolutionOrProject {
            get {
                return ResourceManager.GetString("FileNotAValidSolutionOrProject", resourceCulture);
            }
        }
    }
}
